# Generated by Django 5.0.6 on 2024-06-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0002_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='userId',
        ),
    ]
