# Generated by Django 5.0.6 on 2024-06-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0003_remove_conversation_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='email',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
