# Generated by Django 5.0.6 on 2024-06-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0004_conversation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.BooleanField()),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('translation', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apples.conversation')),
            ],
        ),
    ]
